name: Java Build

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Esegue l'azione ogni giorno a mezzanotte UTC


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository    #checkout della repo
        uses: actions/checkout@v2
        with:
              fetch-depth: 2  #prende gli ultimi 2 commit

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Compile Java files
        run: |
          # Compila solo i file modificati
          modified_files=$(git diff --name-only HEAD~1 HEAD | grep '\.java$')
          if [ -n "$modified_files" ]; then
            javac $modified_files
          else
            echo "Nessun file Java modificato."
            exit 0
          fi
